### PR TITLE
Fix workman_p.png

### PR DESCRIPTION
**Pull request by yous**
Brought from https://web.archive.org/web/20160101123411/http://www.workmanlayout.com/blog/.

### CODE REVIEW

**Comment by kdeloach** [comment]
Thanks for the contribution. Could you describe the changes? I don't see any differences:

image

For this project, all images were originally downloaded from http://web.archive.org.

**Comment by yous** [comment]
Oops, I couldn't see the current image because of my local cache. It seems like a broken image, so I've found the previous image for fix (at least for my local machine). I can see the current image on my phone now, so you can close this.

Sorry for confusion!

**Comment by yous** [comment]
Ah, please wait a moment. I can see your image on comment, but I still can't see the repo's image.

**Comment by kdeloach** [comment]
No problem. I'll look into this some more to see if I can reproduce the issue on other machines/browsers.

**Comment by yous** [comment]
The current `workman_p.png` is actually RIFF file:

```
$ file workman_p.png
workman_p.png: RIFF (little-endian) data, Web/P image, VP8 encoding, 900x300, Scaling: [none]x[none], YUV color, decoders should clamp
```

while `workman_layout.png` is PNG:

```
$ file workman_layout.png
workman_layout.png: PNG image data, 780 x 260, 8-bit colormap, non-interlaced
```

This may cause Safari not to display `workman_p.png`. You can also check that this pull request changes `workman_p.png` to PNG:

```
$ wget https://github.com/yous/kdeloach-workman/raw/workman_p/images/workman_p.png
$ file workman_p.png
workman_p.png: PNG image data, 900 x 300, 8-bit/color RGBA, non-interlaced
```

But I'm not sure why it has changed from PNG to RIFF in the original website.

**Comment by kdeloach** [comment]
Ha, good catch! Merging now.

**Comment by yous** [comment]
Thank you!

**Pull request merged**
